### PR TITLE
settings pane with volume sliders

### PR DESCRIPTION
**Pull request by chrisfarms**
## what

replaces the mute button with a "settings" button that opens some settings for volume controls

Screenshot 2024-10-25 at 11 27 38

volume settings persist past resets

## why

so we can choose to have sfx without music not just everything on or off

* resolves: #202 
* resolves: #214

### CODE REVIEW

**Review by Steedie — APPROVED** [review]
very nice! all works.

perhaps for a new issue: the settings cog looks a bit weird on my windows device when it's that small and bright:
image

might be better to make it bigger/darker

**Comment by chrisfarms** [comment]
It's same on macos... it was made horribly bright as a result of a previous issue saying it was too subtle/dark ... I'm camp subtle, but I won't die on this hill hehe 

maybe there's a nicer cog icon in the symbols list tho that doesn't look like a snowflake

**Comment by Steedie** [comment]
> maybe there's a nicer cog icon in the symbols list tho that doesn't look like a snowflake

`tune`? 👀

image

**Comment by chrisfarms** [comment]
that's def nicer ... but I don't think it's as recognisable as a cog to mean "go here to mess with settings" .... cog will do for now, if we run out of tasks we can go icon shopping heh

**Pull request merged**
