### PR TITLE
More tweaking

### LINKED ISSUE #124: ship incorrectly flashes when shooting
the "ship flash" triggers when losing health ... this made sense back when firing bullets didn't cost health and when it was more than one shot kill ... but now you just flash whenever you shoot which I don't think is intended

### PR DESCRIPTION
**Pull request by PlaymintPaul**
- Ships no longer flash when health changes
- Bullets always fire from the tip of the ship
- Bullets inherit some velocity from the ship
- Zoomed the min and max camera in a little bit
- Made bullet radius smaller

Fixes #124

### CODE REVIEW

**Comment by ldunnplaymint** [comment]
https://github.com/user-attachments/assets/491a4ee3-fcc5-4d10-9097-053f7daa0c3a

I think that it's fine but the bullets are flying out of the space in front of the ship still. I think with the larger bullets, it's a bit too far gone to merge. Opinion?

**Comment by PlaymintPaul** [comment]
@ldunnplaymint

I think that's lag. I've tested these settings and most of the time they come out of the right place. Every now and again they do what you are seeing. I can't think of any explanation other than your inputs are coming in later than the simulation

**Comment by PlaymintPaul** [comment]
I've reduced the offset. Most of the time it looks good, although if you turn quickly it looks like the bullet is coming from the center of the ship rather than the gun. However, if we place it at the gun, and you start running behind it looks like the video you posted.

It is probably possible to still your video if you run behind. One of the negatives of making everything faster...

**Comment by ldunnplaymint** [comment]
It is looking better but testing it a bit more, I think you are right about being ahead/behind in some way. You can make it look awful by bumping off a wall while shooting. Will merge it because it's best we play with the new balancing.

**Comment by PlaymintPaul** [comment]
This video shows the issue. Will post in Discord for visibility

https://github.com/user-attachments/assets/3dc27b5a-5abb-4765-b233-733457010ad4

**Pull request merged**
